#!/bin/bash

echo "init kubernetes config"
echo "${KUBE_CA_PEM}" > kube_ca.pem
kubectl config set-cluster default-cluster --server=${KUBE_URL} --certificate-authority="$(pwd)/kube_ca.pem"
kubectl config set-credentials default-admin --token=${KUBE_TOKEN}
kubectl config set-context default --cluster=default-cluster --user=default-admin --namespace ${KUBE_NAMESPACE}
kubectl config use-context default

echo "Deploying $CI_ENVIRONMENT_SLUG with $REGISTRY_ADDR/$NAME_SPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA..."
cat > deployment.yaml <<EOF
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $name
  labels:
    app: $name
spec:
  replicas: $replicas
  template:
    metadata:
      labels:
        app: $name
    spec:
      imagePullSecrets:
      - name: $IMAGE_SECRET
      containers:
      - name: $name
        image: $REMOTE_IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: $SERVER_PORT
EOF
cat deployment.yaml
kubectl apply --force --record -f deployment.yaml
